#!/usr/bin/python3

def raise_exception_msg(message=""):
    raise NameError("Custom message: Name is not defined")
